version: '3'
services:
  nginx:
    container_name: "nginx"
    build: ./docker/nginx
    ports:
      - "8181:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php:
    container_name: "php"
    build: ./docker/php
    volumes:
      - .:/var/www/html
