version: '3.3'
services:
  node_wpapi:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run dev
networks:
  default:
    external:
      name: laradock_backend
